import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-blur" />
        <nav className="flex gap-4 p-4 bg-black text-white">
          <Link href="/">Home</Link>
          <Link href="/blochsphere">Bloch Sphere</Link>
          <Link href="/circuit">Circuit</Link>
          <Link href="/algorithms">Algorithms</Link>
          <Link href="/results">Results</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
